version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: edestory-postgres
    environment:
      POSTGRES_DB: saleor
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: edestory-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: