name: EDEstory Converge (Cloud Run → write URL into repo)

on:
  push:
    branches: [ main ]
    paths: [ ".github/workflows/edestory-converge.yml" ]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write
  issues: write
  id-token: write

jobs:
  converge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub App token
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          installation-id: ${{ vars.GH_INSTALLATION_ID }}

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Deploy Cloud Run (apps/api)
        env:
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        run: |
          set -euxo pipefail
          REGION="europe-west1"
          SERVICE="diary-api-preview"

          gcloud config set project "$PROJECT_ID"
          gcloud config set run/region "$REGION"

          gcloud run deploy "$SERVICE" \
            --source apps/api \
            --allow-unauthenticated \
            --quiet \
            --update-env-vars PORT=8080 \
            --set-secrets DIARY_TOKEN=projects/${PROJECT_ID}/secrets/preview-DIARY_TOKEN:latest \
            --set-secrets DATABASE_URL=projects/${PROJECT_ID}/secrets/preview-DATABASE_URL:latest

          URL="$(gcloud run services describe "$SERVICE" --format='value(status.url)')"
          echo "$URL" > cloud_run_url.txt

      - name: Write outputs into repo (commit via API)
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
        run: |
          set -e
          mkdir -p ops/supervisor
          cp cloud_run_url.txt ops/supervisor/cloud_run_url.txt
          printf '{"cloud_run_url":"%s","ts":"%s"}\n' "$(cat cloud_run_url.txt)" "$(date -u +%FT%TZ)" > ops/supervisor/last_run.json

          # upsert helper
          upsert() {
            local path="$1"
            local msg="$2"
            local sha=""
            sha=$(gh api repos/${{ github.repository }}/contents/$path --jq .sha 2>/dev/null || echo "")
            content=$(base64 -w0 "$path" 2>/dev/null || base64 "$path")
            if [ -n "$sha" ]; then
              gh api -X PUT repos/${{ github.repository }}/contents/$path \
                -f message="$msg" -f content="$content" -f sha="$sha" -f branch="${{ github.ref_name }}"
            else
              gh api -X PUT repos/${{ github.repository }}/contents/$path \
                -f message="$msg" -f content="$content" -f branch="${{ github.ref_name }}"
            fi
          }
          upsert "ops/supervisor/cloud_run_url.txt" "ops(supervisor): write cloud_run_url"
          upsert "ops/supervisor/last_run.json" "ops(supervisor): write last_run json"

      - name: Comment Cloud Run URL to PR #9 (best-effort)
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
        run: |
          set -e
          URL="$(cat cloud_run_url.txt)"
          gh api repos/${{ github.repository }}/issues/9/comments \
            -f body="Cloud Run URL: ${URL}\nSaved in ops/supervisor/cloud_run_url.txt" || true

